name: Workflow
on:
  push:
    branches:
      - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Analisis con SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=laboratorio-final-CZ
            -Dsonar.organization=DevSecOps-USACH-v9-CZapata
              
  SCA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: OWASP Dependency Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.1/dependency-check-11.1.1-release.zip -o dependency-check.zip
          unzip dependency-check.zip -d $HOME/dependency-check
          $HOME/dependency-check/bin/dependency-check.sh \
            --project "laboratorio-final-CZ" \
            --scan . \
            --out ./dependency-check-report \
            --format "ALL"

  Docker:
    needs: SCA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/laboratorio_cz:latest .

      - name: Push image a Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laboratorio_cz

    Trivy:
      needs: Docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Docker Login
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push DOcker
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/laboratorio_cz:latest

        - name: Trivy Scan
          uses: aquasecurity/trivy-action@v0.29.0
          with:
            image-ref: ${{ secrets.DOCKER_USERNAME }}/laboratorio_cz:latest
            format: table
            severity: HIGH,CRITICAL
          continue-on-error: true        
