name: Workflow
on:
  push:
    branches:
      - main

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set Environment Variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Analisis con SonarCloud
        uses: SonarSource/sonarcloud-github-action
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey="laboratorio-final-CZ"
            -Dsonar.organization="DevSecOps-USACH-v9-CZapata"
            projectBaseDir: .
  
  SCA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: OWASP Dependency Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.1/dependency-check-11.1.1-release.zip -o dependency-check.zip
          unzip dependency-check.zip -d $HOME/dependency-check
          $HOME/dependency-check/bin/dependency-check.sh \
            --project "laboratorio-final-CZ" \
            --scan . \
            --out ./dependency-check-report \
            --format "ALL"

